### ISSUE TITLE
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by sayhiahia** [VITA-Group/NeuralLift-360#6]
**when using NeuralLift-360,I got errors when running this lines** 

 File "NeuralLift-360-main/nerf/sd_clipguide.py", line 68, in __init__
    self.text_encoder = CLIPTextModel.from_pretrained(sd_name, subfolder="text_encoder").to(self.device)

**where the error is**

OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.

**The detailed error information is as follows**

NeRFNetwork(
  (encoder): GridEncoder: input_dim=3 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(6119864, 2) gridtype=hash align_corners=False
  (sigma_net): MLP_swish(
    (net): Sequential(
      (0): ResLinear(
        (nn): Linear(in_features=32, out_features=96, bias=True)
      )
      (1): SiLU(inplace=True)
      (2): ResLinear(
        (nn): Linear(in_features=96, out_features=96, bias=True)
      )
      (3): SiLU(inplace=True)
      (4): ResLinear(
        (nn): Linear(in_features=96, out_features=4, bias=True)
      )
    )
  )
  (encoder_bg): FreqEncoder: input_dim=3 degree=4 output_dim=27
  (bg_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=27, out_features=32, bias=True)
      (1): Linear(in_features=32, out_features=3, bias=True)
    )
  )
)
[INFO] try to load hugging face access token from the default place, make sure you have run `huggingface-cli login`.
[INFO] loading stable diffusion...
Traceback (most recent call last):
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/configuration_utils.py", line 604, in _get_config_dict
    user_agent=user_agent,
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/utils/hub.py", line 290, in cached_path
    local_files_only=local_files_only,
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/utils/hub.py", line 486, in get_from_cache
    _raise_for_status(r)
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/utils/hub.py", line 409, in _raise_for_status
    raise EntryNotFoundError(f"404 Client Error: Entry Not Found for url: {request.url}")
transformers.utils.hub.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/config.json
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/lw/Downloads/pycharm-community-2023.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lw/Downloads/pycharm-community-2023.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lw/tsg/NeuralLift-360-main/main.py", line 77, in <module>
    guidance = StableDiffusion(opt, device, sd_name=opt.sd_name)
 
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/modeling_utils.py", line 1595, in from_pretrained
    **kwargs,
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/models/clip/configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/configuration_utils.py", line 548, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/lw/miniconda3/envs/tsg_nerf_neurallift-360/lib/python3.6/site-packages/transformers/configuration_utils.py", line 622, in _get_config_dict
    f"{pretrained_model_name_or_path} does not appear to have a file named {configuration_file}."
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named config.json.
python-BaseException
Backend TkAgg is interactive backend. Turning interactive mode on.

**Any ideas on why this happens?**

**Comment by Ir1d** [comment]
Hi @sayhiahia Thanks for your interest. Can you please try upgrading the diffusers version? The config.json exists in this directory and should be ok to load https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder

**Comment by sayhiahia** [comment]
> 嗨，感谢您的关注。你能尝试升级扩散器版本吗？config.json 存在于此目录中，应该可以加载 https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder

Thx for your reply.
I've tried to replicate the environment with
> conda env create -f environment.yml
But there is a new error

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0

failed

CondaEnvException: Pip failed
```

**Comment by Ir1d** [comment]
@sayhiahia maybe try removing the `clip==1.0` 🤔
